[package]
name = "math_core"
version = "0.1.0"
edition = "2021"            # ← change 2024 → 2021

[dependencies]

[dev-dependencies]
cbindgen = "0.29.0"

[lib]
crate-type = ["staticlib"]   # spelling must be crate-type

