name: CI
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build-windows-msys2:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          submodules: recursive
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-make
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-pkg-config
            mingw-w64-x86_64-raylib
      - name: Build
        shell: msys2 {0}
        run: |
          set -e
          mkdir -p build
          SRC=$(find . -name "*.cpp" -not -path "./third_party/*")
          echo "Compiling: $SRC"
          g++ -std=c++17 -O2 $SRC -o build/main.exe $(pkg-config --cflags --libs raylib) -mwindows
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: win-build
          path: build/main.exe
